### ISSUE TITLE
Edge Support

### ISSUE THREAD

**Issue by fearfulsmtry** [revolunet/webaudio-wav-stream-player#9]
Working well in Chrome. Any chance we could get some support for Edge? 

Getting WEBAUDIO17014: Decoding error: The stream provided is corrupt or unsupported.

**Comment by revolunet** [comment]
Hi
I dont think Edge handle fetch streams yet
Looks like there is some hope with this polyfill though : https://www.npmjs.com/package/fetch-readablestream

**Comment by fearfulsmtry** [comment]
Thanks for your response. I tried that polyfill and no luck. Thankfully it's no longer required to work on Edge.
